### ISSUE TITLE
Refactor the source code tree

### ISSUE THREAD

**Issue by vinitshahdeo** [CodeChefVIT/anotator#4]
**The source tree layout should reflect the architecture**; as a corollary, a well-structured architecture can lead to a well-structured source tree layout.

The code must be structured in different modules/folders. For your project, I suggest you to have similar code structure - 

* assets
    - images

* css
  - custom ```your stylesheets```
  - vendor ```external stylesheets/frameworks say bootstrap```

* js
   - custom ``` your own scripts```
   - lib ``` external JS libraries say underscore.js etc. ```

* `index.html` (home page)

* `README.md`

@Murgowt @muskantewari, Please make the changes.

**Comment by muskantewari** [comment]
resolved

**Comment by vinitshahdeo** [comment]
**Awesome:)**

Closing this issue.
@muskantewari
